

<div style="text-align: justify">

# Introducción 



Construir sociedades más democráticas es un objetivo internacional consagrado por la Organización de las Naciones Unidas tanto en la Declaración Universal de los Derechos Humanos como en el Pacto internacional de los Derechos Civiles y Políticos. Basándose en estos tratados internacionales, para que una sociedad sea efectivamente democrática son requisitos fundamentales una amplia participación de la ciudadanía y que la participación sea representativa, es decir, que no tenga sesgos socioeconómicos, raciales, de género, o de cualquier otra razón. Actualmente podemos decir que múltiples democracias poseen conflictos respecto a estas dos condiciones. En primer lugar, existe una tendencia a la disminución en la participación politica [@tezanos-pinto_Participacion_2015; @herrmann_Disminucion_2016;@diaz_Dimensiones_2017; @janmaat_Civic_2013; @contreras_DIFERENCIAS_2013; @galston_Civic_2007]. En segundo lugar, la participación politica es desigual, perjudicando la representación de la voz politica de sectores más pobres, de grupos racializados, de las mujeres y de los más jóvenes [@verba_Would_2003; @lijphart_Unequal_1997; @desposato_Gender_2009;@coffe_Explaining_2020; @hutchings_CENTRALITY_2004]. Más aun, estas desigualdades políticas se transmiten de manera intergeneracional [@brady_Political_2015]. En el caso Chileno, tanto el Centro de Estudio de Conflicto y Cohesión Social (COES) como el Programa de las Naciones Unidas para el Desarrollo (PNUD) han señalado que existe una gran desigualdad en la participación política, la cual sobrerrepresenta los grupos acomodados del país favoreciendo la reproducción de la desigualdad [@joignant_Desigualdades_2017; @palet_Desiguales_2017].

Con el objetivo de fomentar valores democráticos en los ciudadanos y afrontar los desafíos de las democracias, cada vez más países, entre ellos chile, han incorporado en sus planes de estudio un mayor espacio para temáticas ciudadanas [@keer_ciudadania_2015]. La escuela es un lugar estratégico para fomentar valores, principios y conductas democráticas, pues en ella se realiza un proceso de socialización donde los estudiantes incorporan normas sociales necesarias para la vida en su comunidad [@durkheim_Educacion_2010]. En torno a la socialización ciudadana de los jóvenes en las escuelas existen más de cuarenta años acumulados de investigaciones desde las ciencias sociales [@torney_Crossnational_1979]. Estas investigaciones han evidenciado reiteradamente que los estudiantes de distintos grupos socioeconómicos poseen distintas actitudes e intenciones de participación, lo cual es un obstáculo para la realización de la democracia [@castillo_Social_2014;@miranda_Political_2018;@ferrans_Civic_2017;@trevino_Influence_2017].

Además de estudiar las actitudes y conductas políticas de los estudiantes, desde 1990, existe un esfuerzo por medir y estudiar las capacidades cognitivas de los jóvenes para su vida ciudadana [@torney-purta_estudio_2015]. Este esfuerzo derivó en la prueba de conocimiento Cívico y Ciudadano la cual fue aplicada en tres encuestas internacionales de formación cívica. Según los creadores de la escala, esta busca medir tanto el conocimiento que poseen los estudiantes de sus sistemas políticos, como las habilidades cognitivas que poseen para reflexionar sobre situaciones concretas a partir de principios democráticos y su conocimiento político [@schulz_Initial_2010]. Existe contundente evidencia para señalar que un mayor conocimiento cívico se relaciona con mejores actitudes democráticas como la participación y la tolerancia [@schulz_Initial_2010; @galston_Civic_2007;@miranda_Political_2018]. Una de las conclusiones más relevante de estos estudios es que existe una transmisión intergeneracional de la desigualdad politica,  es decir, estudiantes hijos de padres con mejor situación económica, posen mejores conocimientos y habilidades para desenvolverse en la vida politica [@schulz_Initial_2010; @miranda_Desigualdad_2015]. Respecto a esta desigualdad, si bien se ha señalado que está estrechamente relacionada con aspectos de desigualdad cultural (p. ej. Educación de los padres y cantidad de libros en el hogar) y transmisión de actitudes, se ha dado poca relevancia a la transmisión de habilidades que ayudan a reproducir la desigualdad en la política [@brady_Political_2015]. En torno a las habilidades, la organización de Estados Americanos (OEA) señala que la carencia en alfabetización puede ser un obstáculo para la educación cívica en Chile [@torney-purta_estudio_2015]. Esta advertencia de la OEA, y algunas investigaciones que demuestran la dificultad de los estudiantes al leer la prueba por el lenguaje relativamente abstracto y complejo [@zhang_Understanding_2015;@arensmeier_Swedish_2015], sugieren que el manejo del lenguaje posee un rol relevante para comprender las abstractas temáticas ciudadanas jugando un rol en la reproducción de la desigualdad política. 

En consideración de lo señalado, la pregunta de esta investigación es: 

> ¿Cuál es el rol que juega el manejo del lenguaje en la transmisión intergeneracional de la desigualdad politica? 

Esta investigación busca evidenciar la importancia del manejo del lenguaje para explicar las desigualdades en habilidades políticas, frente a otras explicaciones alternativas basadas en la trasmisión de valores democrticos. Al explicar la reproducción intergeneracional de los conocimientos y habilidades políticas, las investigaciones recurren a dos líneas teóricas de la socialización: _la actitudinal_, centrada en la transmisión de valores e intereses, y _la cognitiva_, centrada en la transmisión de habilidades [@miranda_Political_2018]. La propuesta de esta investigación plantea que la desigualdad de las habilidades cívico-ciudadanas se explica en una buena medida por desigualdades en habilidades, y más específicamente, por el manejo del lenguaje. 

Esta propuesta no solo se sustenta en el efecto de la cultura académica de los padres en las habilidades políticas, sino también en que la comprensión lectora requiere de las mismas destrezas cognitivas que el conocimiento cívico (Ej. Comprender, interpretar, analizar, evaluar, entre otras). Por ejemplo,  para que un joven logre identificar una acción como antidemocrática, como alguien insultando a un inmigrante por su origen, no solo debe ser capaz de comprender que una persona le grita a otra, sino que debe _interpretar_ cual es el sentido de esa acción y ser capaz de _evaluar la relación_   entre dicho sentido y los principios democráticos, habilidades semejantes a las necesarias para la comprensión lectora. De este modo, para poseer un buen conocimiento cívico no solo es necesario poseer valores ciudadanos, sino habilidades reflexivas del lenguaje.

El considerar que la comprensión de la vida cívica puede estar asociada a la comprensión del lenguaje no solo es relevante dentro del campo de la educación, sino también en el campo de la acción política y la democracia. Si un joven es capas de comprender mediante el lenguaje distintos ideales democráticos es más probable que actúe y opine en concordancia con ellos. Más aun, el comprender distintos ideales puede abrir las posibilidades de acción del sujeto ya que, la si la realidad es social y construida mediante el lenguaje, poseer un mayor manejo del lenguaje implica una mayor capacidad reflexiva sobre la realidad, una mayor capacidad critica y, por ende, una mayor capacidad de agencia. El lenguaje no solo nos permite enunciar el mundo, sino que tambien nos ayuda a analizarlo, criticarlo y así actuar reflexivamente sobre él. 

En suma, se propone que el manejo del lenguaje posee una mejor capacidad mediadora que otras variables usualmente consideradas relevantes para explicar la desigualdad en el conocimiento Cívico, como puede ser el interés político. Si bien, efectivamente participar en un contexto de mayor capital cultural puede motivar un mayor interés político, el poseer este valor democrático no significa necesariamente que el estudiante posea la capacidad de interpretar una situación y evaluar su relación con dicho ideal. Por el contrario, poseer un mayor manejo del lenguaje implica mayores capacidades cognitivas de diversos tipos que probablemente facilitan la comprensión del mundo político, la interiorización de conocimientos cívicos y la capacidad de evaluar diversas posturas. Si bien tanto intereses como habilidades son fundamentales para el desarrollo de un sujeto participativo, para explicar particularmente los conocimientos cívicos, es comprensible que las habilidades posean un mayor efecto. 


> Hipótesis general: La desigualdad social del conocimiento civico se debe parcialmente a las habilidades diferentes en el manejo del lenguaje.

Evidenciar que el manejo del lenguaje es capaz de explicar en alguna medida la desigualdad social del conocimiento cívico es un aporte sustantivo a la teoría de la socialización política. Que el lenguaje juegue un rol en las habilidades políticas daría cuenta de su importancia para la vida democratica tanto para comprender sus conceptos como para actuar de modo ciudadano. Esto es un aporte al modelo de recursos, pues permite profundizar en la comprensión del mecanismo causal de la reproducción social de la desigualdad politica, respecto a la transmisión de habilidades, como @brady_Political_2015 sugerían necesario. 

Además, evidenciar el rol del lenguaje en el conocimiento cívico puede ser muy provechoso para las políticas públicas, ya que contar con información del contexto de aplicación del nuevo curso de formación ciudadana nos permite anticiparnos a sus posibles obstáculos. En primer lugar, podríamos suponer que la aplicación de un nuevo ramo de educación cívica, en el contexto de un socialmente desigual manejo del lenguaje, podría incrementar las brechas sociales en la materia, dado que los colegios de mayor nivel socioeconómico poseen un mayor manejo del lenguaje y por ello se encuentran en mejores condiciones para incorporar los conocimientos cívicos. En consideración de esta posibilidad, seria provechoso para el objetivo del ramo, realizar planes de reforzamiento colectivo en lenguaje para aquellos colegios que poseen menores indicadores en las pruebas estandarizadas de comprensión lectora. En consideración del mismo argumento y considerando las inequidades dentro de los estudiantes de un mismo curso, podría ser provechoso prestar asistencia psicopedagógica a estudiantes que posean un menor manejo del lenguaje, antes de que estos se enfrenten en el último ciclo de educación a la formación ciudadana. Para evaluar estas medidas, es necesario comprobar la capacidad que posee el lenguaje para disminuir la desigualdad de habilidades políticas.

A partir de las inquietudes y propuestas planteadas hasta ahora, se establecen los siguientes objetivos de Investigación.


* Objetivo general: Comprender el rol que cumple la desigualdad social del manejo del lenguaje en la influencia del origen socioeconómico sobre el conocimiento cívico y ciudadano.


* Objetivos específicos: 

    + Evaluar la relación entre comprensión lectora y conocimiento cívico incorporando factores influyentes señalados por la literatura.

    + Contrastar si la desigualdad social del conocimiento cívico se explica por las diferencias de comprensión lectoras o por la transmisión de interés político.

    + Evaluar la capacidad que posee la comprensión lectora para resolver la desigualdad social del conocimiento cívico.





