



# Conclusiones

En consideracion de los resultados, podemos entregar algunas respuestas parciales a nuestros objetivos de investigación.

En primer lugar, podemos decir que existe una relación moderadamente alta entre el conocimiento Cívico y la comprensión lectora, relación la cual no solo se mantiene al incluir otras variables fundamentales en el modelo, sino que es capaz de controlar buena parte del efecto de las variables de origen social. La evidencia del efecto de la comprensión lectora, no niega el efecto positivo sobre el conocimiento Cívico que pueden tener variables como la cultura democrática del establecimiento, lo cual se evidencia con la mantención de este efecto al controlar por comprensión lectora.

En segundo lugar, en función de los resultados, podemos decir que aquellas teorías que explicaban la relación entre NSE y conocimiento cívico, por la transmisión de valores, si bien son ciertas, poseen una visión parcial de lo que ocurre ya que en buena medida la desigualdad social del conocimiento cívico se relaciona ampliamente con la desigualdad social de la comprensión lectora, la cual se relaciona con el capital cultural objetivado de los padres (más de 100 libros en el hogar) y el acceder a buena educación. Es decir, no es tanto que los padres adinerados eduquen democráticamente a sus hijos, sino que más bien, ya sea por transmisión directa o por acceso a buena educación, les otorgan un mayor manejo del lenguaje, lo cual les permite igualmente incorporar de manera más compleja la realidad política, teniendo más herramientas para comprender, analizar y criticar políticamente.

En tercer lugar, gracias a la evidencia, podemos señalar que la comprensión lectora puede ser una forma de mejorar el conocimiento Cívico en sectores vulnerables, puesto que estudiantes de dichos sectores que si poseen un buen manejo del lenguaje poseen igualmente altas capacidades y conocimientos para la vida ciudadana. En función de lo anterior, se hace necesario estudiar experimentalmente el efecto que podría tener un reforzamiento en lenguaje para la prueba de la ICCS.

##  Discusión

Dados los resultados, y el rol prominente de la comprensión lectora en el conocimiento Cívico, se hace necesario revisar algunas propuestas que intentan explicar el conocimiento Cívico, puesto que pueden caer en resultados espurios al no considerar una variable relevante dentro de sus modelos. 

En términos teóricos esta investigación ayuda a profundizar la comprensión de la reproducción social de la desigualdad politica, como @brady_Political_2015 sugerían necesario para avanzar en este campo. Estos resultados evidencias que las diferencias sociales en habilidades políticas, no se deben tanto a la transmisión de valores democráticos, como a la transmisión de habilidades relacionadas con el manejo del lenguaje. 

Igualmente, se hace necesario profundizar hasta qué punto la comprensión lectora es necesaria para la vida política o más bien es un problema de error de medida, en el cual se incorpora varianza no deseada a la escala. En consideracion de lo anterior, es posible que, al generar instrumentos con menores niveles de abstracción en la redacción de las situaciones y preguntas, se generen menores diferencias de conocimiento Cívico entre distintos grupos sociales. 

Respecto a cuáles son los caminos que deben tomarse para mejorar la desigualdad en el conocimiento cívico y en la participación ciudadana, resulta evidente después de los resultados, que además de reforzar la educación cívica en los colegios como ya se está haciendo (y debe seguirse haciendo, debe fomentarse la comprensión lectora). Incluso podemos decir que cuando se posee altos niveles de comprensión lectora, las diferencias de estatus socioeconómico no afectan de manera sustancial, existiendo estudiantes de colegios con bajo nivel económico que poseen una buena comprensión lectora y cívica. Al respecto, tipos de clases que impliquen lectura colectiva y discusión sobre lo leído, para entender en conjunto el sentido de los textos, puede ser una muy buena estrategia, puesto que está demostrado que los profesores que realizan dichas actividades mejoran el puntaje en lenguaje de sus estudiantes (Lorena Ortega) así como que aulas más participativas poseen un efecto para el conocimiento cívico. Es en dichos espacios de participación donde puede sacarse el provecho al capital cultural de cada estudiante y fomentar el efecto par.

En relación al nuevo plan de formación ciudadana, y considerando estos resultados es sensato esperar un efecto diferencial de la política en cada establecimiento según el nivel de comprensión lectora del colegio, lo cual está relacionado con el nivel socioeconómico. Quizás sea prudente en miras del objetivo de la política, prestar ayuda especializada a colegios que posean bajos niveles de comprensión lectora. Dentro de los colegios prestar apoyo a los estudiantes con dificultades al respecto también puede ser una buena medida a aplicar en cursos anteriores al último ciclo de tercero cuarto, donde deberán aplicar dichas habilidades en la reflexión ciudadana y en la incorporación de conocimientos cívicos.

El considerar que la comprensión de la vida cívica puede estar asociada a la comprensión del lenguaje no solo es relevante dentro del campo de la educación, sino también en el campo de la acción política y la democracia. Si un joven es capas de comprender mediante el lenguaje distintos ideales democráticos es más probable que actúe y opine en concordancia con ellos. Más aun, el comprender distintos ideales puede abrir las posibilidades de acción del sujeto ya que, la si la realidad es social y construida mediante el lenguaje, poseer un mayor manejo del lenguaje implica una mayor capacidad reflexiva sobre la realidad, una mayor capacidad critica y, por ende, una mayor capacidad de agencia. El lenguaje no solo nos permite enunciar el mundo, sino que tambien nos ayuda a analizarlo, criticarlo y así actuar reflexivamente sobre él. 


Además, evidenciar el rol del lenguaje en el conocimiento cívico puede ser muy provechoso para las políticas públicas, ya que contar con información del contexto de aplicación del nuevo curso de formación ciudadana nos permite anticiparnos a sus posibles obstáculos. En primer lugar, podríamos suponer que la aplicación de un nuevo ramo de educación cívica, en el contexto de un socialmente desigual manejo del lenguaje, podría incrementar las brechas sociales en la materia, dado que los colegios de mayor nivel socioeconómico poseen un mayor manejo del lenguaje y por ello se encuentran en mejores condiciones para incorporar los conocimientos cívicos. En consideración de esta posibilidad, seria provechoso para el objetivo del ramo, realizar planes de reforzamiento colectivo en lenguaje para aquellos colegios que poseen menores indicadores en las pruebas estandarizadas de comprensión lectora. En consideración del mismo argumento y considerando las inequidades dentro de los estudiantes de un mismo curso, podría ser provechoso prestar asistencia psicopedagógica a estudiantes que posean un menor manejo del lenguaje, antes de que estos se enfrenten en el último ciclo de educación a la formación ciudadana. Para evaluar estas medidas, es necesario comprobar la capacidad que posee el lenguaje para disminuir la desigualdad de habilidades políticas.
