---
title: '<span style="color: #D88712;">  Desigualdad, política y lenguaje</span>: El rol del manejo del lenguaje en la transmisión intergeneracional de las habilidades políticas en jóvenes chilenos  '
subtitle: "Tesis para optar al grado de Magister"
author: "Francisco Javier Meneses Rivas"
date: "Santiago de Chile, año 2022" # o para fecha actual: "`r Sys.Date()`"
institution: "Universidad de Chile"
degree: "Tesis para optar al grado de Magister en Ciencias Sociales"
advisor: "Profesor guía \n Juan Carlos Castillo"
bibliography: 
    - tesis.bib
    - civiclengu.bib
    - comprencioncivica.bib
    - concivcomleng.bib
biblio-style: apalike
link-citations: yes
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
lof: True
lot: True
---



# Resumen {-}

Actualmente las democracias se encuentran frente a una crisis de legitimidad que se relaciona, entre otras cosas, con la falta de representación de distintos grupos, como los sectores populares y los jóvenes. Al respecto, las investigaciones han señalado que no solo existen diferencias actitudinales hacia la política según grupo social, sino que también existen brechas en las habilidades políticas que se relacionan con la participación desigual. La asociación internacional para la evaluación del logro educativo (IEA) ha desarrollado el Estudio Internacional de Educación Cívica y Formación Ciudadana (ICCS) que se enfoca en estudiar las Habilidades y Conocimientos necesarios para la vida ciudadana en jóvenes estudiantes. El conocimiento cívico de la ICCS ha generado interés en distintos investigadores puesto que se asocia positivamente con un conjunto de actitudes democráticas como la participación y la tolerancia. Se ha demostrado que existe una relación entre nivel socioeconómico y conocimiento Cívico. Al explicar esta desigualdad algunos autores han señalado que en familias de alto capital cultural se genera un ambiente más ciudadano y académico, que implica una socialización en valores políticos y habilidades cognitivas. Para profundizar esta línea de investigación, se propone que parte de lo que explica la relación entre desigualdad social y conocimiento cívico es el manejo del lenguaje, esto basado en una visión sociológica del lenguaje como elemento cohesionador, crítico y transmisible. Para evaluar esta hipótesis se trabajaron conjuntamente los datos de la ICCS y el SIMCE (N = 3140). A partir de los análisis de mediación multinivel, se concluye que la transmisión intergeneracional de la desigualdad habilidades políticas se explica más por habilidades en el lenguaje que por la transmisión de intereses político. Además, se evidencia el potencial del lenguaje para disminuir la desigualdad de habilidades políticas, lo cual debe considerarse  para la implementación del ramo de formación ciudadana.

Palabras clave: Conocimiento Cívico, Desigualdad política, Comprensión lectora, Interés político


# Agradecimientos {-}

Deseo profundamente poder agradecer en estas páginas a más de las personas de las que caben en ellas. Por lo pronto, es menester agradecer a mis padres que con su esfuerzo pudieron educarme y darme con ello mejores posibilidades de vida. 
Agradecer directamente a mi pareja Anais Herrera junto con quien desperté el interés por la sociología y junto a quien he tenido las reflexiones que han dado vida a esta tesis.

También quiero agradecer muy sinceramente al profesor Juan Carlos Castillo quien me ha ayudado a profesionalizarme en estos últimos años y quien me presentó el marco de investigación al que intenta aportar esta tesis. En la misma línea quisiera agradecer a Felipe Ruiz que fue el primero en dedicarse a enseñarme el uso del Software R el cual ha sido mi herramienta fundamental de trabajo. Finalmente deseo agradecer a Julio Iturra como mi primer colega de trabajo de quién aprendido muchas cosas prácticas que no se incorporaron en mi formación universitaria.

Fuera de lo personal deseo agradecer a todas las personas y científicos que han contribuido a la construcción colectiva del conocimiento. Agradecer especialmente a quienes en consonancia con la ciencia abierta han compartido sus conocimientos ayudándome progresar. Entre ellos agradezco especialmente a Yihui Xie quien ha democratizado múltiples herramientas digitales, haciéndolas más fáciles de usar sin la necesidad de ser un erudito de la programación.
